image: fireroaddigital/firepod:1.0.0

tasks:
  - name: terminal
    before: |
      .gitpod/env-setup.sh
      .gitpod/ddev-in-gitpod-setup.sh
    init: |
      ddev debug download-images
      .gitpod/project-setup.sh
    command: |
      echo y | ddev start
      gp preview $(gp url 8080)

# Set the following ports public
ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 5000
    onOpen: open-preview
  - port: 6006
    onOpen: open-preview
  - port: 6942
    onOpen: ignore
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore

# github:
#   prebuilds:
#     # enable for the master/default branch (defaults to true)
#     master: true
#     # enable for all branches in this repo (defaults to false)
#     branches: true
#     # enable for pull requests coming from this repo (defaults to true)
#     pullRequests: true
#     # enable for pull requests coming from forks (defaults to false)
#     pullRequestsFromForks: true
#     # add a check to pull requests (defaults to true)
#     addCheck: true
#     # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
#     addComment: true
#     # add a "Review in Gitpod" button to the pull request's description (defaults to false)
#     addBadge: true
#     # add a label once the prebuild is ready to pull requests (defaults to false)
#     addLabel: true
